<?php

return array (
  0 => 
  array (
    'index' => 1003,
    'id' => 'about-2',
    'elementId' => 'about-3',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-2.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Content Column Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  1 => 
  array (
    'index' => 1004,
    'id' => 'about-3',
    'elementId' => 'about-4',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-3.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'content-bg-color\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Bg. Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'content-bg-color\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  2 => 
  array (
    'index' => 1006,
    'id' => 'about-5',
    'elementId' => 'about-6',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-5.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.center-overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  3 => 
  array (
    'index' => 1007,
    'id' => 'about-6',
    'elementId' => 'about-7',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-6.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-6.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.offset-double-border-overlay .border-1\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  4 => 
  array (
    'index' => 1008,
    'id' => 'about-7',
    'elementId' => 'about-8',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-7.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-7.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.center-overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  5 => 
  array (
    'index' => 1009,
    'id' => 'about-8',
    'elementId' => 'about-9',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-8.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-8.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Border Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.center-overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-color\',value)})}}}',
  ),
  6 => 
  array (
    'index' => 1011,
    'id' => 'about-image-text',
    'elementId' => 'about-11',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-image-text.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-image-text.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  7 => 
  array (
    'index' => 1013,
    'id' => 'about-text-image',
    'elementId' => 'about-13',
    'type' => 'section-available',
    'name' => 'About',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-text-image.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-text-image.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Section Options"),init:function($container){var contentbgcolor=CP_Customizer.createControl.color(this.getPrefixed(\'contentbgcolor\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Content Column Color\')});this.addToControlsList(contentbgcolor)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\'] \',selector=\'.content-col\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background-color\');this.getControl(\'contentbgcolor\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'background-color\',value)})}}}',
  ),
  8 => 
  array (
    'index' => 1015,
    'id' => 'blog-section-card',
    'elementId' => 'latest-news-2',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-blog-section-card.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/blog-section-card.png',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  9 => 
  array (
    'index' => 1016,
    'id' => 'blog-section-colored',
    'elementId' => 'latest-news-3',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-blog-section-colored.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/blog-section-colored.png',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("Blog Section Options"),init:function($container){var color=CP_Customizer.createControl.color(this.getPrefixed(\'color\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Card Border Color\')});this.addToControlsList(color)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\']\',selector=\' .post-content[class*=bottom-border-]\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-bottom-color\');this.getControl(\'color\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-bottom-color\',value)})}}}',
  ),
  10 => 
  array (
    'index' => 1017,
    'id' => 'blog-section-simple',
    'elementId' => 'latest-news-4',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-blog-section-simple.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/blog-section-simple.png',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  11 => 
  array (
    'index' => 1019,
    'id' => 'clients-2',
    'elementId' => 'clients-2',
    'type' => 'section-available',
    'name' => 'Clients',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-clients-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/clients-2.png',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  12 => 
  array (
    'index' => 1020,
    'id' => 'clients-3',
    'elementId' => 'clients-3',
    'type' => 'section-available',
    'name' => 'Clients',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-clients-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/clients-3.png',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  13 => 
  array (
    'index' => 1023,
    'id' => 'contact-3',
    'elementId' => 'contact-2',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-contact-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/contact-3.png',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  14 => 
  array (
    'index' => 1024,
    'id' => 'contact-4',
    'elementId' => 'contact-3',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-contact-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/contact-4.png',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  15 => 
  array (
    'index' => 1025,
    'id' => 'contact-5',
    'elementId' => 'contact-4',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-contact-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/contact-5.png',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  16 => 
  array (
    'index' => 1026,
    'id' => 'contact-6',
    'elementId' => 'contact-5',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-contact-6.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/contact-6.png',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  17 => 
  array (
    'index' => 1027,
    'id' => 'contact-7',
    'elementId' => 'contact-6',
    'type' => 'section-available',
    'name' => 'Contact',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-contact-7.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/contact-7.png',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true,revertClassesHolder:\'.map-col\'}',
  ),
  18 => 
  array (
    'index' => 1028,
    'id' => 'content-1',
    'elementId' => 'content-1',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-1.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  19 => 
  array (
    'index' => 1029,
    'id' => 'content-10',
    'elementId' => 'content-2',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-10.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-10.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  20 => 
  array (
    'index' => 1030,
    'id' => 'content-11',
    'elementId' => 'content-3',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-11.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-11.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  21 => 
  array (
    'index' => 1032,
    'id' => 'content-13',
    'elementId' => 'content-5',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-13.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-13.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  22 => 
  array (
    'index' => 1033,
    'id' => 'content-14',
    'elementId' => 'content-6',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-14.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-14.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  23 => 
  array (
    'index' => 1034,
    'id' => 'content-15',
    'elementId' => 'content-7',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-15.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-15.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(-10%, -10%)",width:"100%",height:"100%"}}}}',
  ),
  24 => 
  array (
    'index' => 1035,
    'id' => 'content-16',
    'elementId' => 'content-8',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-16.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-16.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(10%, -10%)",width:"100%",height:"100%"}}}}',
  ),
  25 => 
  array (
    'index' => 1036,
    'id' => 'content-17',
    'elementId' => 'content-9',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-17.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-17.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(5%, -5%)",width:"100%",height:"100%"}}}}',
  ),
  26 => 
  array (
    'index' => 1037,
    'id' => 'content-18',
    'elementId' => 'content-10',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-18.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-18.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(-5%, -5%)",width:"100%",height:"100%"}}}}',
  ),
  27 => 
  array (
    'index' => 1038,
    'id' => 'content-19',
    'elementId' => 'content-11',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-19.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-19.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  28 => 
  array (
    'index' => 1039,
    'id' => 'content-19-2',
    'elementId' => 'content-12',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-19-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-19-2.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canRevertColumnsOnMobile:true}',
  ),
  29 => 
  array (
    'index' => 1042,
    'id' => 'content-5',
    'elementId' => 'content-15',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-5.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'.row.content-holder\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(-5%, 5%)",width:"100%",height:"100%"}}}}',
  ),
  30 => 
  array (
    'index' => 1043,
    'id' => 'content-5-2',
    'elementId' => 'content-16',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-5-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-5-2.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'.row.content-holder\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(5%, 5%)",width:"100%",height:"100%"}}}}',
  ),
  31 => 
  array (
    'index' => 1044,
    'id' => 'content-6',
    'elementId' => 'content-17',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-6.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-6.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(10%, 10%)",width:"100%",height:"100%"}}}}',
  ),
  32 => 
  array (
    'index' => 1045,
    'id' => 'content-6-2',
    'elementId' => 'content-18',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-6-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-6-2.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'modules.export={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(-10%, 10%)",width:"100%",height:"100%"}}}}',
  ),
  33 => 
  array (
    'index' => 1048,
    'id' => 'content-9',
    'elementId' => 'content-21',
    'type' => 'section-available',
    'name' => 'Content',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-9.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-9.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  34 => 
  array (
    'index' => 1052,
    'id' => 'cta-centered-bg-section',
    'elementId' => 'cta-2',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-cta-centered-bg-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/cta-centered-bg-section.png',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  35 => 
  array (
    'index' => 1053,
    'id' => 'cta-centered-section-grid',
    'elementId' => 'cta-3',
    'type' => 'section-available',
    'name' => 'Cta',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-cta-centered-section-grid.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/cta-centered-section-grid.png',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  36 => 
  array (
    'index' => 1055,
    'id' => 'features-12-card',
    'elementId' => 'features-2',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-12-card.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-12-card.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  37 => 
  array (
    'index' => 1057,
    'id' => 'features-12-card-bordered-colored',
    'elementId' => 'features-4',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-12-card-bordered-colored.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-12-card-bordered-colored.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bottom-border-"]\',prefix:\'bottom-border-\',suffix:\'\'}}]}',
  ),
  38 => 
  array (
    'index' => 1059,
    'id' => 'features-13-card',
    'elementId' => 'features-6',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-13-card.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-13-card.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  39 => 
  array (
    'index' => 1061,
    'id' => 'features-13-card-bordered-colored',
    'elementId' => 'features-8',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-13-card-bordered-colored.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-13-card-bordered-colored.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bottom-border-"]\',prefix:\'bottom-border-\',suffix:\'\'}}]}',
  ),
  40 => 
  array (
    'index' => 1064,
    'id' => 'features-16-card-bordered-colored',
    'elementId' => 'features-11',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-16-card-bordered-colored.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-16-card-bordered-colored.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bottom-border-"]\',prefix:\'bottom-border-\',suffix:\'\'}}]}',
  ),
  41 => 
  array (
    'index' => 1065,
    'id' => 'features-5',
    'elementId' => 'features-12',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-5.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  42 => 
  array (
    'index' => 1066,
    'id' => 'features-6',
    'elementId' => 'features-13',
    'type' => 'section-available',
    'name' => 'Features',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-6.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-6.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  43 => 
  array (
    'index' => 1067,
    'id' => 'gallery-1',
    'elementId' => 'gallery-1',
    'type' => 'section-available',
    'name' => 'Gallery',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-gallery-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/gallery-1.png',
    'description' => 'Gallery',
    'category' => 'gallery',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  44 => 
  array (
    'index' => 1068,
    'id' => 'gallery-2',
    'elementId' => 'gallery-2',
    'type' => 'section-available',
    'name' => 'Gallery',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-gallery-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/gallery-2.png',
    'description' => 'Gallery',
    'category' => 'gallery',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  45 => 
  array (
    'index' => 1070,
    'id' => 'overlappable-1',
    'elementId' => 'overlappable-1',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-overlappable-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/overlappable-1.png',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  46 => 
  array (
    'index' => 1071,
    'id' => 'overlappable-2',
    'elementId' => 'overlappable-2',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-overlappable-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/overlappable-2.png',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false}',
  ),
  47 => 
  array (
    'index' => 1072,
    'id' => 'overlappable-3',
    'elementId' => 'overlappable-3',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-overlappable-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/overlappable-3.png',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false}',
  ),
  48 => 
  array (
    'index' => 1074,
    'id' => 'overlappable-5',
    'elementId' => 'overlappable-5',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-overlappable-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/overlappable-5.png',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,customColor:[{colorClass:{selector:\'.col-padding[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  49 => 
  array (
    'index' => 1075,
    'id' => 'overlappable-6',
    'elementId' => 'overlappable-6',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-overlappable-6.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/overlappable-6.png',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro-only' => true,
    'export' => 'module.exports={allowSectionTitleOptions:false,customColorDefault:\'#FF9800\',customColor:[{colorClass:{selector:\'.col-padding-small[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  50 => 
  array (
    'index' => 1076,
    'id' => 'portfolio-1',
    'elementId' => 'portfolio-1',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-portfolio-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/portfolio-1.png',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  51 => 
  array (
    'index' => 1077,
    'id' => 'portfolio-3',
    'elementId' => 'portfolio-2',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-portfolio-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/portfolio-3.png',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  52 => 
  array (
    'index' => 1080,
    'id' => 'portfolio-6',
    'elementId' => 'portfolio-5',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-portfolio-6.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/portfolio-6.png',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  53 => 
  array (
    'index' => 1081,
    'id' => 'pricing-1',
    'elementId' => 'pricing-1',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-pricing-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/pricing-1.png',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'ul\',prefix:\'decoration-\',suffix:\'\'}},{colorClass:{selector:"p.custom-color",prefix:\'\',suffix:\'\'}},{colorClass:{selector:".button",prefix:\'\',suffix:\'\'}}]}',
  ),
  54 => 
  array (
    'index' => 1082,
    'id' => 'pricing-2',
    'elementId' => 'pricing-2',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-pricing-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/pricing-2.png',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.card\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  55 => 
  array (
    'index' => 1083,
    'id' => 'pricing-3',
    'elementId' => 'pricing-3',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-pricing-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/pricing-3.png',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  56 => 
  array (
    'index' => 1084,
    'id' => 'pricing-4',
    'elementId' => 'pricing-4',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-pricing-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/pricing-4.png',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  57 => 
  array (
    'index' => 1085,
    'id' => 'pricing-5',
    'elementId' => 'pricing-5',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-pricing-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/pricing-5.png',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  58 => 
  array (
    'index' => 1086,
    'id' => 'pricing-6',
    'elementId' => 'pricing-6',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-pricing-6.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/pricing-6.png',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.card\',prefix:\'card-\',suffix:\'\'}}]}',
  ),
  59 => 
  array (
    'index' => 1087,
    'id' => 'pricing-7',
    'elementId' => 'pricing-7',
    'type' => 'section-available',
    'name' => 'Pricing',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-pricing-7.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/pricing-7.png',
    'description' => 'Pricing',
    'category' => 'pricing',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  60 => 
  array (
    'index' => 1088,
    'id' => 'subscribe-2cols-section',
    'elementId' => 'subscribe-1',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-subscribe-2cols-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/subscribe-2cols-section.png',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  61 => 
  array (
    'index' => 1089,
    'id' => 'subscribe-centered-section',
    'elementId' => 'subscribe-2',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-subscribe-centered-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/subscribe-centered-section.png',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  62 => 
  array (
    'index' => 1090,
    'id' => 'subscribe-social-section',
    'elementId' => 'subscribe-3',
    'type' => 'section-available',
    'name' => 'Subscribe',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-subscribe-social-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/subscribe-social-section.png',
    'description' => 'Subscribe',
    'category' => 'subscribe',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  63 => 
  array (
    'index' => 1091,
    'id' => 'team-1',
    'elementId' => 'team-1',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-team-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/team-1.png',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bottom-border-"]\',prefix:\'bottom-border-\',suffix:\'\'}}]}',
  ),
  64 => 
  array (
    'index' => 1093,
    'id' => 'team-3',
    'elementId' => 'team-3',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-team-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/team-3.png',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColorDefault:\'#000000\',customColor:[{colorClass:{selector:\'[data-hover-fx] .overlay\',prefix:\'grad-180-transparent-\',suffix:\'\'}}]}',
  ),
  65 => 
  array (
    'index' => 1094,
    'id' => 'team-4',
    'elementId' => 'team-4',
    'type' => 'section-available',
    'name' => 'Team',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-team-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/team-4.png',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  66 => 
  array (
    'index' => 1097,
    'id' => 'testimonials-2',
    'elementId' => 'testimonials-2',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-testimonials-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/testimonials-2.png',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bottom-border-"]\',prefix:\'bottom-border-\',suffix:\'\'}}]}',
  ),
  67 => 
  array (
    'index' => 1098,
    'id' => 'testimonials-3',
    'elementId' => 'testimonials-3',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-testimonials-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/testimonials-3.png',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  68 => 
  array (
    'index' => 1099,
    'id' => 'testimonials-4',
    'elementId' => 'testimonials-4',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-testimonials-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/testimonials-4.png',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  69 => 
  array (
    'index' => 1101,
    'id' => 'woocommerce-section',
    'elementId' => 'woocommerce-1',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-woocommerce-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/woocommerce-section.png',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  70 => 
  array (
    'index' => 1102,
    'id' => 'woocommerce-section-colored',
    'elementId' => 'woocommerce-2',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-woocommerce-section-colored.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/woocommerce-section-colored.png',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("WooCommerce Section Options"),init:function($container){var color=CP_Customizer.createControl.color(this.getPrefixed(\'color\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Card Border Color\')});this.addToControlsList(color)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\']\',selector=\' .woocommerce ul.products li.product .ope-woo-card-item.card[class*=bottom-border-]\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentColor=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'border-bottom-color\');this.getControl(\'color\').attachWithSetter(currentColor,function(value){CP_Customizer.contentStyle.setProp(styleSelector,null,\'border-bottom-color\',value)})}}}',
  ),
  71 => 
  array (
    'index' => 1103,
    'id' => 'woocommerce-section-shadow',
    'elementId' => 'woocommerce-3',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-woocommerce-section-shadow.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/woocommerce-section-shadow.png',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => NULL,
  ),
  72 => 
  array (
    'index' => 1104,
    'id' => 'woocommerce-section-shadowed-image',
    'elementId' => 'woocommerce-4',
    'type' => 'section-available',
    'name' => 'Woocommerce',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-woocommerce-section-shadowed-image.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/woocommerce-section-shadowed-image.png',
    'description' => 'Woocommerce',
    'category' => 'woocommerce',
    'prepend' => false,
    'pro-only' => true,
    'export' => 'module.exports={sectionArea:{areaTitle:window.CP_Customizer.translateCompanionString("WooCommerce Section Options"),init:function($container){var color=CP_Customizer.createControl.color(this.getPrefixed(\'color\'),$container,{value:\'#ffffff\',label:window.CP_Customizer.translateCompanionString(\'Overlay color\')});this.addToControlsList(color)},update:function(data){var dataId=\'[data-id=\'+data.section.attr(\'data-id\')+\']\',selector=\' li .contentswap-effect .overlay\',item=data.section.find(selector).eq(0),styleSelector=dataId+selector,currentGradient=CP_Customizer.contentStyle.getNodeProp(item,styleSelector,null,\'background\'),currentColor=CP_Customizer.styleUtils.getCSSGradientColors(currentGradient,true).pop().value.toHexString();this.getControl(\'color\').attachWithSetter(currentColor,function(value){var opacity=CP_Customizer.styleUtils.getRGBAStringTransparency(value);value=CP_Customizer.styleUtils.generateOneSideLinerGradient(180,value);CP_Customizer.contentStyle.setProp(styleSelector,null,\'background\',value);CP_Customizer.contentStyle.setProp(styleSelector,null,\'opacity\',opacity)})}}}',
  ),
);
