<?php

return array (
  0 => 
  array (
    'index' => 1001,
    'id' => 'about-1',
    'elementId' => 'about-1',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-1" data-export-id="about-1" data-category="about" class="about-1 content-section"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Brand new WordPress theme&nbsp;<span href="#" style="font-weight:700;font-family:Playfair Display,sans-serif;font-style:italic;">with unlimited power</span>&nbsp;and customization possibilities<br></h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud.</p></div> </div> <div class="row"> <div class="button-holder space-bottom space-bottom-small" data-type="column"> <a class="button color1" href="#">GET STARTED NOW</a></div> <div class="col-xs bottom-xs flexbox image-group-bottom-3-img space-bottom-xs center-xs"> <img class="left-img shadow-large-black" data-size="500x300" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"> <img class="center-img shadow-large-black" data-size="500x300" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"> <img class="right-img shadow-large-black" data-size="500x300" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-1.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  1 => 
  array (
    'index' => 1002,
    'id' => 'about-10',
    'elementId' => 'about-2',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-10" data-export-id="about-10" data-category="about" class="about-10 content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 space-bottom-xs content-column" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 flexbox middle-xs center-xs space-bottom-xs"><div class="overlay-box middle-xs center-xs flexbox"> <div class="overlay-box-offset offset-border shadow-medium border-color1 hide-xs"></div> <img class="shadow-large" data-size="485x705" src="[tag_companion_uri]/sections/images/about-img-5.jpg"/></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-10.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-10.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(15%, 5%)",width:"100%",height:"100%","z-index":-1}}}}',
  ),
  2 => 
  array (
    'index' => 1005,
    'id' => 'about-4',
    'elementId' => 'about-5',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-4" data-export-id="about-4" data-category="about" class="about-4 content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 space-bottom-xs" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 flexbox center-xs middle-xs image-group-2-img"> <img class="img-1 shadow-large" data-size="250x200" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"/> <img class="img-2 shadow-large" data-size="220x170" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"/></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-4.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true}',
  ),
  3 => 
  array (
    'index' => 1010,
    'id' => 'about-9',
    'elementId' => 'about-10',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-9" data-export-id="about-9" data-category="about" class="about-9 content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 space-bottom-xs content-column content-right-sm" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 flexbox flexbox middle-xs center-xs space-bottom-xs"><div class="overlay-box flexbox middle-xs center-xs overlay-holder "> <div class="overlay-box-offset offset-background shadow-medium bg-color2 hide-xs"></div> <img class="flexbox shadow-large img1" src="[tag_companion_uri]/sections/images/urban-438393.jpg" data-size="600x400"/></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-9.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-9.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,sectionStyle:{"nomedia":{".overlay-box .overlay-box-offset":{transform:"translate(31%,-8%)",width:"83%",height:"113%"}}}}',
  ),
  4 => 
  array (
    'index' => 1012,
    'id' => 'about-images-right-section',
    'elementId' => 'about-12',
    'type' => 'section-available',
    'name' => 'About',
    'content' => '<div data-label="About" data-id="about-images-right-section" data-export-id="about-images-right-section" data-category="about" class="about-images-right-section content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm text-center"><div class="col-sm-5 content-left-sm" data-type="column"> <h5>LOREM IPSUM DOLOR</h5> <h2>Enjoy the best <br/> <span style="font-family:Playfair Display,sans-serif;font-weight:700;font-style:italic;" href="#">design and functions</span> combined together</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">GET STARTED NOW</a></div> <div class="col-sm-7 space-bottom-xs"><div class="image-group-side-3-img"> <img class="topimg shadow-large" src="[tag_companion_uri]/sections/images/people-2605526.jpg"/> <img class="rightimg shadow-large" src="[tag_companion_uri]/sections/images/background-2498615.jpg"/> <div class="leftimg"> <img class="shadow-large" src="[tag_companion_uri]/sections/images/woman-1209584.jpg"/></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-about-images-right-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/about-images-right-section.png',
    'description' => 'About',
    'category' => 'about',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true,flexAligns:[\'.image-group-side-3-img\']}',
  ),
  5 => 
  array (
    'index' => 1014,
    'id' => 'blog-section',
    'elementId' => 'latest-news-1',
    'type' => 'section-available',
    'name' => 'Latest-news',
    'content' => '<div data-label="Latest-news" data-id="blog-section" data-export-id="blog-section" data-category="latest_news" class="blog-section blog-section-standard content-section content-section-spacing"><div class="gridContainer"> <div class="row"><div data-type="column" class="section-title-col"> <h2>Latest News</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div> </div> <div class="row"> <div data-type="row" data-dynamic-columns="handled" data-content-shortcode="mesmerize_latest_news">[mesmerize_latest_news]</div></div> <div class="row"><div class="text-center"> <a class="button color1" data-attr-shortcode="href:mesmerize_blog_link" href="[mesmerize_blog_link]">SEE ALL BLOG POSTS</a></div> </div></div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-blog-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/blog-section.png',
    'description' => 'Latest-news',
    'category' => 'latest_news',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  6 => 
  array (
    'index' => 1018,
    'id' => 'clients-1',
    'elementId' => 'clients-1',
    'type' => 'section-available',
    'name' => 'Clients',
    'content' => '<div data-label="Clients" data-id="clients-1" data-export-id="clients-1" data-category="clients" class="clients-1 content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm"><div data-type="column" class="col-sm-6 space-bottom-xs"> <h2 class="font-700">Our Happy Clients</h2> <p class="lead">A Right Media Mix Can Make The Difference</p></div> <div class="col-sm-6"><div data-type="row" class="row spaced-cols center-xs padding-lr"> <div class="col-xs-3"> <img src="[tag_companion_uri]/sections/images/logo1.png" class="desaturate"/></div> <div class="col-xs-3"> <img src="[tag_companion_uri]/sections/images/logo2.png" class="desaturate"/></div> <div class="col-xs-3"> <img src="[tag_companion_uri]/sections/images/logo3.png" class="desaturate"/></div> <div class="col-xs-3"> <img src="[tag_companion_uri]/sections/images/logo4.png" class="desaturate"/></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-clients-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/clients-1.png',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  7 => 
  array (
    'index' => 1021,
    'id' => 'clients-4',
    'elementId' => 'clients-4',
    'type' => 'section-available',
    'name' => 'Clients',
    'content' => '<div data-label="Clients" data-id="clients-4" data-export-id="clients-4" data-category="clients" class="clients-4 content-section content-section-spacing-small"><div class="gridContainer"> <div class="row"><div data-type="column" class="section-title-col"> <h2 class="font-700">Our Happy Clients</h2> <p class="lead">A Right Media Mix Can Make The Difference</p></div> </div> <div data-type="row" class="row spaced-cols middle-xs center-xs space-bottom padding-lr"> <div class="col-xs-6 col-sm-2"> <img src="[tag_companion_uri]/sections/images/logo1.png"/></div> <div class="col-xs-6 col-sm-2"> <img src="[tag_companion_uri]/sections/images/logo2.png"/></div> <div class="col-xs-6 col-sm-2"> <img src="[tag_companion_uri]/sections/images/logo3.png"/></div> <div class="col-xs-6 col-sm-2"> <img src="[tag_companion_uri]/sections/images/logo4.png"/></div> <div class="col-xs-6 col-sm-2"> <img src="[tag_companion_uri]/sections/images/logo1.png"/></div> <div class="col-xs-6 col-sm-2"> <img src="[tag_companion_uri]/sections/images/logo2.png"/></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-clients-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/clients-4.png',
    'description' => 'Clients',
    'category' => 'clients',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false}',
  ),
  8 => 
  array (
    'index' => 1022,
    'id' => 'contact-1',
    'elementId' => 'contact-1',
    'type' => 'section-available',
    'name' => 'Contact',
    'content' => '<div data-label="Contact" data-id="contact-1" data-export-id="contact-1" data-category="contact" class="contact-1 content-section content-section-spacing white-text" data-parallax-depth="20"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Contact us</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row text-center"> <div class="col-xs-12 col-sm-8 col-sm-offset-2 contact-form-wrapper inline-info"> <div class="card large-padding"> <div class="" data-content-shortcode="mesmerize_contact_form" data-editable="true">[mesmerize_contact_form]</div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-contact-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/contact-1.png',
    'description' => 'Contact',
    'category' => 'contact',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  9 => 
  array (
    'index' => 1031,
    'id' => 'content-12',
    'elementId' => 'content-4',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-12" data-export-id="content-12" data-category="content" class="content-12 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>This is one of the things we do best</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row center-xs middle-xs"> <div class="col-sm-9" data-type="column"> <img class="shadow-large" src="[tag_companion_uri]/sections/images/apple-1838564-big.jpg"></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-12.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-12.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  10 => 
  array (
    'index' => 1040,
    'id' => 'content-2',
    'elementId' => 'content-13',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-2" data-export-id="content-2" data-category="content" class="content-2 content-section content-section-spacing"><div> <div class="row middle-xs"><div class="col-sm-5 bg-image shadow-large-black" data-bg="image"></div> <div class="col-sm-7 full-col-left-padding full-col-right-padding"> <div class="row"> <div data-type="column" class="space-bottom-small content-title-col"> <h5>CASE STUDY</h5> <h2>The Secret of Success</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div> </div> <div class="row spaced-cols " data-type="row"> <div class="col-xs-6" data-type="column"> <h5>CAMERA</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> <div class="col-xs-6" data-type="column"><h5>MUSIC CENTER</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> <div class="col-xs-6" data-type="column"><h5>MESSAGES</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> <div class="col-xs-6" data-type="column"><h5>CHANNELS</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-2.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'.content-title-col\'],canRevertColumnsOnMobile:true}',
  ),
  11 => 
  array (
    'index' => 1041,
    'id' => 'content-3',
    'elementId' => 'content-14',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-3" data-export-id="content-3" data-category="content" class="content-3 content-section content-section-spacing"><div> <div class="row middle-xs"><div class="col-sm-7 full-col-left-padding full-col-right-padding"> <div class="row"><div data-type="column" class="space-bottom-small content-title-col"> <h5>CASE STUDY</h5> <h2>The Secret of Success</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-6" data-type="column"> <h5>CAMERA</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> <div class="col-xs-6" data-type="column"><h5>MUSIC CENTER</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> <div class="col-xs-6" data-type="column"><h5>MESSAGES</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> <div class="col-xs-6" data-type="column"><h5>CHANNELS</h5> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p></div> </div></div> <div class="col-sm-5 bg-image shadow-large-black revert-classes-holder" data-bg="image"></div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-3.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-3.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'.content-title-col\'],canRevertColumnsOnMobile:true,revertClassesHolder:\'.revert-classes-holder\'}',
  ),
  12 => 
  array (
    'index' => 1046,
    'id' => 'content-7',
    'elementId' => 'content-19',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-7" data-export-id="content-7" data-category="content" class="content-7 content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm"><div class="col-sm-6 space-bottom-xs" data-type="column"> <h2>This is one of the things <br>we do best&nbsp;</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">LEARN MORE</a></div> <div class="col-sm-6" data-type="column"> <img class="shadow-large" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-7.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-7.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\']}',
  ),
  13 => 
  array (
    'index' => 1047,
    'id' => 'content-8',
    'elementId' => 'content-20',
    'type' => 'section-available',
    'name' => 'Content',
    'content' => '<div data-label="Content" data-id="content-8" data-export-id="content-8" data-category="content" class="content-8 content-section content-section-spacing"><div class="gridContainer"> <div class="row middle-sm"><div class="col-sm-6 space-bottom-xs space-top-xs" data-type="column"> <img class="shadow-large" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"></div> <div class="col-sm-6" data-type="column"><h2>This is one of the things <br>we do best&nbsp;</h2> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p> <a class="button color1" href="#">LEARN MORE</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-content-8.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/content-8.png',
    'description' => 'Content',
    'category' => 'content',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={contentAligns:[\'[data-type="column"]:not(.section-title-col)\'],canRevertColumnsOnMobile:true}',
  ),
  14 => 
  array (
    'index' => 1049,
    'id' => 'counters-1',
    'elementId' => 'counters-1',
    'type' => 'section-available',
    'name' => 'Counters',
    'content' => '<div data-label="Counters" data-id="counters-1" data-export-id="counters-1" data-category="counters" class="counters-1 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Counters</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row spaced-cols" data-type="row" data-fixed="true"> <div class="col-xs-12 col-sm-4 space-bottom-small col-padding-xs"> <div class="circle-counter color1"> <svg class="circle-svg" viewBox="0 0 100 100"> <circle r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle> <circle class="circle-bar" r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle></svg> <div class="circle-content"><h2 class="font-100" data-min="0" data-max="100" data-stop="50" data-prefix="" data-suffix="%" data-countup="true"></h2> <p>Design</p></div> </div></div> <div class="col-xs-12 col-sm-4 space-bottom-small col-padding-xs"><div class="circle-counter color2"> <svg class="circle-svg" viewBox="0 0 100 100"><circle r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle> <circle class="circle-bar" r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle></svg> <div class="circle-content"><h2 class="font-100" data-min="0" data-max="100" data-stop="75" data-prefix="" data-suffix="%" data-countup="true"></h2> <p>Development</p></div> </div></div> <div class="col-xs-12 col-sm-4 space-bottom-small col-padding-xs"><div class="circle-counter color4"> <svg class="circle-svg" viewBox="0 0 100 100"><circle r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle> <circle class="circle-bar" r="48" stroke-linecap="round" cx="50" cy="50" fill="transparent" stroke-dasharray="301.6" stroke-dashoffset="301.6px"></circle></svg> <div class="circle-content"><h2 class="font-100" data-min="0" data-max="100" data-stop="90" data-prefix="" data-suffix="%" data-countup="true"></h2> <p>SEO Expertize</p></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-counters-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/counters-1.png',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false,customColor:[{colorClass:{selector:\'.circle-counter\',prefix:\'\',suffix:\'\'}}]}',
  ),
  15 => 
  array (
    'index' => 1050,
    'id' => 'counters-2',
    'elementId' => 'counters-2',
    'type' => 'section-available',
    'name' => 'Counters',
    'content' => '<div data-label="Counters" data-id="counters-2" data-export-id="counters-2" data-category="counters" class="counters-2 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Counters</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row" data-type="row"> <div class="col-xs-12 col-sm-4 text-center space-bottom"> <i class="fa fa-envira icon color1"></i> <h3 class="font-400" data-min="0" data-max="80" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true" style="display:inline-block;"></h3> <h5 class="upper color2">predefined themes</h5></div> <div class="col-xs-12 col-sm-4 text-center space-bottom"><i class="fa fa-smile-o icon color1"></i> <h3 class="font-400" data-min="10000" data-max="15000" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true" style="display:inline-block;"></h3> <h5 class="upper color2">happy clients</h5></div> <div class="col-xs-12 col-sm-4 text-center space-bottom"><i class="fa fa-trophy icon color1 "></i> <h3 class="font-400" data-min="0" data-max="25" data-duration="2000" data-prefix="" data-suffix="+" data-countup="true" style="display:inline-block;"></h3> <h5 class="upper color2">awards</h5></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-counters-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/counters-2.png',
    'description' => 'Counters',
    'category' => 'counters',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false,}',
  ),
  16 => 
  array (
    'index' => 1051,
    'id' => 'cta-blue-section',
    'elementId' => 'cta-1',
    'type' => 'section-available',
    'name' => 'Cta',
    'content' => '<div data-label="Cta" data-id="cta-blue-section" data-export-id="cta-blue-section" data-category="cta" class="cta-blue-section content-section content-section-spacing-medium bg-color1 white-text"><div class="gridContainer"> <div class="row middle-xs"><div class="col-sm-8 space-bottom-xs" data-type="column"> <h2>Join us! <span class="font-300">It will only take a minute</span></h2> </div> <div class="col-sm-4 end-sm" data-type="column"> <a class="button color2" href="#">GET STARTED TODAY</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-cta-blue-section.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/cta-blue-section.png',
    'description' => 'Cta',
    'category' => 'cta',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  17 => 
  array (
    'index' => 1054,
    'id' => 'features-12',
    'elementId' => 'features-1',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-12" data-export-id="features-12" data-category="features" class="features-12 content-section content-section-spacing "><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-sm-6"> <div class="row space-bottom"> <div class="col-sm-fit icon-column"> <i class="fa icon fa-connectdevelop round bordered color2"></i> </div> <div class="col-sm" data-type="column"> <h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> <div class="col-sm-6"><div class="row space-bottom"> <div class="col-sm-fit icon-column"><i class="fa icon fa-codepen round bordered color2"></i></div> <div class="col-sm" data-type="column"><h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> <div class="col-sm-6"><div class="row space-bottom"> <div class="col-sm-fit icon-column"><i class="fa icon fa-cube round bordered color2"></i></div> <div class="col-sm" data-type="column"><h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> <div class="col-sm-6"><div class="row space-bottom"> <div class="col-sm-fit icon-column"><i class="fa icon fa-database round bordered color2"></i></div> <div class="col-sm" data-type="column"><h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-12.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-12.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  18 => 
  array (
    'index' => 1056,
    'id' => 'features-12-card-bordered',
    'elementId' => 'features-3',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-12-card-bordered" data-export-id="features-12-card-bordered" data-category="features" class="features-12-card-bordered content-section content-section-spacing "><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-sm-6"> <div class="card row-card bordered y-move"> <div class="row"> <div class="col-sm-fit icon-column"> <i class="fa icon fa-connectdevelop round bordered color2"></i> </div> <div class="col-sm" data-type="column"> <h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div> <div class="col-sm-6"> <div class="card row-card bordered y-move"> <div class="row"> <div class="col-sm-fit icon-column"> <i class="fa icon fa-codepen round bordered color2"></i> </div> <div class="col-sm" data-type="column"> <h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div> <div class="col-sm-6"> <div class="card row-card bordered y-move"> <div class="row"> <div class="col-sm-fit icon-column"> <i class="fa icon fa-cube round bordered color2"></i> </div> <div class="col-sm" data-type="column"> <h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div> <div class="col-sm-6"> <div class="card row-card bordered y-move"> <div class="row"> <div class="col-sm-fit icon-column"> <i class="fa icon fa-database round bordered color2"></i> </div> <div class="col-sm" data-type="column"> <h5 class="color2">FLEXIBLE CODE</h5> <p class="">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-12-card-bordered.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-12-card-bordered.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  19 => 
  array (
    'index' => 1058,
    'id' => 'features-13',
    'elementId' => 'features-5',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-13" data-export-id="features-13" data-category="features" class="features-13 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col col-sm-6 col-md-3 space-bottom"> <i class="fa icon fa-connectdevelop big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color2" href="#">GET STARTED</a></div> <div class="col col-sm-6 col-md-3 space-bottom"><i class="fa icon fa-connectdevelop big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color2" href="#">GET STARTED</a></div> <div class="col col-sm-6 col-md-3 space-bottom"><i class="fa icon fa-connectdevelop big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color2" href="#">GET STARTED</a></div> <div class="col col-sm-6 col-md-3 space-bottom"><i class="fa icon fa-codepen big round bordered color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color2" href="#">GET STARTED</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-13.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-13.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  20 => 
  array (
    'index' => 1060,
    'id' => 'features-13-card-bordered',
    'elementId' => 'features-7',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-13-card-bordered" data-export-id="features-13-card-bordered" data-category="features" class="features-13 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-sm-4"> <div class="card bordered y-move" data-type="column"> <i class="fa icon fa-codepen big round reverse color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color2" href="#">GET STARTED</a></div> </div> <div class="col-sm-4"> <div class="card bordered y-move" data-type="column"> <i class="fa icon fa-codepen big round reverse color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color2" href="#">GET STARTED</a></div> </div> <div class="col-sm-4"> <div class="card bordered y-move" data-type="column"> <i class="fa icon fa-codepen big round reverse color1"></i> <h4>FLEXIBLE CODE</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="button small y-move color2" href="#">GET STARTED</a></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-13-card-bordered.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-13-card-bordered.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  21 => 
  array (
    'index' => 1062,
    'id' => 'features-16',
    'elementId' => 'features-9',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-16" data-export-id="features-16" data-category="features" class="features-16 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-4 space-bottom"> <img class="face" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="read-more">learn more</a></div> </div> <div class="col-xs-12 col-sm-6 col-md-4 space-bottom"> <img class="face" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="read-more">learn more</a></div> </div> <div class="col-xs-12 col-sm-6 col-md-4 space-bottom"> <img class="face" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p> <a class="read-more">learn more</a></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-16.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-16.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  22 => 
  array (
    'index' => 1063,
    'id' => 'features-16-card-bordered',
    'elementId' => 'features-10',
    'type' => 'section-available',
    'name' => 'Features',
    'content' => '<div data-label="Features" data-id="features-16-card-bordered" data-export-id="features-16-card-bordered" data-category="features" class="features-16-card-bordered content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>A few things we’re great at</h2> <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.Ut enim ad minim veniam, quis nostrud exercitation.</p></div> </div> <div class="row spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-4"> <div class="card no-padding bordered y-move"> <img class="face" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class=" col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> <div class="col-xs-12 col-sm-6 col-md-4"><div class="card no-padding bordered y-move"> <img class="face" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class=" col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> <div class="col-xs-12 col-sm-6 col-md-4"><div class="card no-padding bordered y-move"> <img class="face" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"> <div data-type="column" class=" col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Responsive Design</h4> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation.</p></div> <div data-type="column" class=" col-padding-small col-padding-small-xs read-more-container"><a class="read-more">learn more</a></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-features-16-card-bordered.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/features-16-card-bordered.png',
    'description' => 'Features',
    'category' => 'features',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  23 => 
  array (
    'index' => 1073,
    'id' => 'overlappable-4',
    'elementId' => 'overlappable-4',
    'type' => 'section-available',
    'name' => 'Overlappable',
    'content' => '<div data-label="Overlappable" data-id="overlappable-4" data-export-id="overlappable-4" data-category="overlappable" class="overlappable-4 content-section content-section-spacing" data-overlap="true"><div class="gridContainer"> <div data-type="row" class="row spaced-cols text-center"><div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-clone large shadow-large-black round aligncenter reverse color1"></i> <div data-type="column"> <h5>RESPONSIVE DESIGN</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-cogs large shadow-large-black round aligncenter reverse color1"></i> <div data-type="column"><h5>SUPER FEATURES</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div> <div class="col-xs-12 col-sm-4 col-padding"> <i class="fa icon fa-magic large shadow-large-black round aligncenter reverse color1"></i> <div data-type="column"><h5>DRAG AND DROP</h5> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-overlappable-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/overlappable-4.png',
    'description' => 'Overlappable',
    'category' => 'overlappable',
    'prepend' => true,
    'pro' => false,
    'export' => 'module.exports={allowSectionTitleOptions:false}',
  ),
  24 => 
  array (
    'index' => 1078,
    'id' => 'portfolio-4',
    'elementId' => 'portfolio-3',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'content' => '<div data-label="Portfolio" data-id="portfolio-4" data-export-id="portfolio-4" data-category="portfolio" class="portfolio-4 content-section content-section-spacing-top"><div class=""> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Portfolio</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div data-type="row" class="row" data-fixed="true"> <div class="col-xs-12 col-sm-3 no-gutter-col"> <div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-3 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-3 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-3 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-3 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-3 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-3 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> <div class="col-xs-12 col-sm-3 no-gutter-col"><div class="contentswap-effect " data-hover-fx="portfolio-4"> <div class="initial-image"> <img data-size="542x360" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"></div> <div class="overlay bg-color1"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a href="#"><i class="fa fa-search icon big portfolio-icon" aria-hidden="true"></i></a></div> </div></div> </div></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-portfolio-4.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/portfolio-4.png',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={canAlignRowItemsContent:false,maintainCropPropotion:false,customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  25 => 
  array (
    'index' => 1079,
    'id' => 'portfolio-5',
    'elementId' => 'portfolio-4',
    'type' => 'section-available',
    'name' => 'Portfolio',
    'content' => '<div data-label="Portfolio" data-id="portfolio-5" data-export-id="portfolio-5" data-category="portfolio" class="portfolio-5 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Portfolio</h2> <p class="lead">With the Internet spreading linke wildfire and reaching every part of our daily life, more and more traffic is directed to websites in search for information.</p></div> </div> <div class="row space-bottom spaced-cols" data-type="row"> <div class="col-xs-12 col-sm-4 text-center"> <div class="card no-padding bordered"> <div data-hover-fx="portfolio-6" class="contentswap-effect"> <div class="initial-image"> <img data-size="500x333" src="[tag_companion_uri]/sections/images/computer-2569652.jpg"></div> <div class="overlay bg-color6"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a class="button small color2" href="#">Read More</a></div> </div></div> </div> <div class="col-xs-12"> <div class="space-bottom space-top" data-type="column"> <h5>Project Name</h5> <p class="small italic">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p></div> </div></div> </div> <div class="col-xs-12 col-sm-4 text-center"> <div class="card no-padding bordered"> <div data-hover-fx="portfolio-6" class="contentswap-effect"> <div class="initial-image"> <img data-size="500x333" src="[tag_companion_uri]/sections/images/apple-1838564.jpg"></div> <div class="overlay bg-color6"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a class="button small color2" href="#">Read More</a></div> </div></div> </div> <div class="col-xs-12"> <div class="space-bottom space-top" data-type="column"> <h5>Project Name</h5> <p class="small italic">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p></div> </div></div> </div> <div class="col-xs-12 col-sm-4 text-center"> <div class="card no-padding bordered"> <div data-hover-fx="portfolio-6" class="contentswap-effect"> <div class="initial-image"> <img data-size="500x333" src="[tag_companion_uri]/sections/images/laptop-2559795.jpg"></div> <div class="overlay bg-color6"></div> <div class="swap-inner col-xs-12"> <div class="row full-height-row middle-xs middle-sm"> <div class="col-xs-12 text-center content-holder"> <a class="button small color2" href="#">Read More</a></div> </div></div> </div> <div class="col-xs-12"> <div class="space-bottom space-top" data-type="column"> <h5>Project Name</h5> <p class="small italic">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore</p></div> </div></div> </div></div> <div class="row"><div data-type="column" class="col-xs-12 text-center"> <a class="button color2 y-move" href="#">View Portfolio</a></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-portfolio-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/portfolio-5.png',
    'description' => 'Portfolio',
    'category' => 'portfolio',
    'prepend' => false,
    'pro' => false,
    'export' => 'module.exports={customColor:[{colorClass:{selector:\'div[class*="bg-"]\',prefix:\'bg-\',suffix:\'\'}}]}',
  ),
  26 => 
  array (
    'index' => 1092,
    'id' => 'team-2',
    'elementId' => 'team-2',
    'type' => 'section-available',
    'name' => 'Team',
    'content' => '<div data-label="Team" data-id="team-2" data-export-id="team-2" data-category="team" class="team-2 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Our Team</h2> <p class="lead">There are number of instructions to be followed at the time of refilling an inket cartridge. So whenever your printer ink runs dry you need to follow the below steps for inkjet cartridge refill.</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-1.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-2.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-3.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-2.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-5.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-6.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-7.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-sm-6 col-md-3"> <div class="card y-move no-padding bordered"> <img class="face" src="[tag_companion_uri]/sections/images/team-8.jpg"> <div data-type="column" class="col-padding-small col-padding-small-xs description-container"> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-team-2.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/team-2.png',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  27 => 
  array (
    'index' => 1095,
    'id' => 'team-5',
    'elementId' => 'team-5',
    'type' => 'section-available',
    'name' => 'Team',
    'content' => '<div data-label="Team" data-id="team-5" data-export-id="team-5" data-category="team" class="team-5 content-section content-section-spacing"><div class="gridContainer"> <div class="row text-center"><div class="section-title-col" data-type="column"> <h2>Our Team</h2> <p class="lead">There are number of instructions to be followed at the time of refilling an inket cartridge. So whenever your printer ink runs dry you need to follow the below steps for inkjet cartridge refill.</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-1.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-2.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-3.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-4.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-5.jpg"/> <h4 class="font-500">Team Member</h4> <p class="small" style="font-style:italic">Job Title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-6.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-7.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div> <div class="col-xs-12 col-sm-6 col-md-3 col-padding"> <div class="row "> <div data-type="column" class="col-xs-12 col-sm-12"> <img class="round face" src="[tag_companion_uri]/sections/images/team-8.jpg"/> <h4 class="font-500">Team Member</h4> <p class="italic">job title</p> <p>Point of Sale hardware, the till at a shop check out, has become very complex over the past ten years.</p> <div class="social-icons-group" data-type="group"> <a href="#"><i class="gray fa icon fa-facebook-square small "></i></a> <a href="#"><i class="gray fa icon fa-twitter-square small "></i></a> <a href="#"><i class="gray fa icon fa-linkedin-square small "></i></a> <a href="#"><i class="gray fa icon fa-google-plus-square small "></i></a></div> </div></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-team-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/team-5.png',
    'description' => 'Team',
    'category' => 'team',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  28 => 
  array (
    'index' => 1096,
    'id' => 'testimonials-1',
    'elementId' => 'testimonials-1',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'content' => '<div data-label="Testimonials" data-id="testimonials-1" data-export-id="testimonials-1" data-category="testimonials" class="testimonials-1 content-section content-section-spacing"><div class="gridContainer"> <div class="row"><div data-type="column" class="section-title-col"> <h2>Client Testimonials</h2> <p class="lead">Don\'t take our word for it - here\'s what our clients say:</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-sm-4"> <i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like "Hey, I think I\'ve been here before</p> <img src="[tag_companion_uri]/sections/images/team-5.jpg" class="round icon"> <h5>John Doe</h5> <p class="small" style="font-style:italic">Company name</p></div> <div class="col-sm-4"><i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like "Hey, I think I\'ve been here before</p> <img src="[tag_companion_uri]/sections/images/team-5.jpg" class="round icon"> <h5>John Doe</h5> <p class="small" style="font-style:italic">Company name</p></div> <div class="col-sm-4"><i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like "Hey, I think I\'ve been here before</p> <img src="[tag_companion_uri]/sections/images/team-5.jpg" class="round icon"> <h5>John Doe</h5> <p class="small" style="font-style:italic">Company name</p></div> </div></div> </div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-testimonials-1.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/testimonials-1.png',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
  29 => 
  array (
    'index' => 1100,
    'id' => 'testimonials-5',
    'elementId' => 'testimonials-5',
    'type' => 'section-available',
    'name' => 'Testimonials',
    'content' => '<div data-label="Testimonials" data-id="testimonials-5" data-export-id="testimonials-5" data-category="testimonials" class="testimonials-5 content-section content-section-spacing"><div class="gridContainer"> <div class="row"><div data-type="column" class="section-title-col"> <h2>Client Testimonials</h2> <p class="lead">Don\'t take our word for it - here\'s what our clients say:</p></div> </div> <div class="row spaced-cols content-center-sm" data-type="row"> <div class="col-sm-4"> <div class="card y-move bordered" data-type="column"> <i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="text-center">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like “Hey, I think I\'ve been here before,</p> <img src="[tag_companion_uri]/sections/images/team-5.jpg" class="round icon"> <h6>John Doe</h6> <p class="small italic">Company name</p></div> </div> <div class="col-sm-4"> <div class="card y-move bordered" data-type="column"> <i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="text-center">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like “Hey, I think I\'ve been here before,</p> <img src="[tag_companion_uri]/sections/images/team-5.jpg" class="round icon"> <h6>John Doe</h6> <p class="small italic">Company name</p></div> </div> <div class="col-sm-4"> <div class="card y-move bordered" data-type="column"> <i class="fa fa-quote-right icon color1 small quotation-icon"></i> <p class="text-center">Do you sometimes have the feeling that you\'re running into the same obstacles over and over again? Many of my conflicts have the same feel to them, like “Hey, I think I\'ve been here before,</p> <img src="[tag_companion_uri]/sections/images/team-5.jpg" class="round icon"> <h6>John Doe</h6> <p class="small italic">Company name</p></div> </div></div> </div></div>',
    'thumb' => '//extendthemes.com/assets/mesmerize/previews/sections/thumb-testimonials-5.png',
    'preview' => '//extendthemes.com/assets/mesmerize/previews/sections/testimonials-5.png',
    'description' => 'Testimonials',
    'category' => 'testimonials',
    'prepend' => false,
    'pro' => false,
    'export' => NULL,
  ),
);
